extends: default

rules:
  braces:
    max-spaces-inside: 1
  comments-indentation: false
  comments:
    min-spaces-from-content: 1
  document-start: disable
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: true
#
# SPDX-FileCopyrightText: 2025 Keith Maxwell <keith.maxwell@gmail.com>
# SPDX-License-Identifier: CC0-1.0
# vim: set ft=yaml :
