# .github/workflows/main.yaml
# Copyright 2023 Keith Maxwell
# SPDX-License-Identifier: CC0-1.0

on: # yamllint disable-line rule:truthy
  push:
    branches: [main]
    tags: [v*]
  pull_request: { branches: [main] }
  workflow_dispatch:

jobs:
  renovate-config-validator:
    # yamllint disable-line rule:line-length
    uses: maxwell-k/dotlocalslashbin/.github/workflows/renovate.yaml@a33ce13bfa55aac3dbc6658478e1e91c55003020 # v0.0.18
  nox:
    # yamllint disable-line rule:line-length
    uses: maxwell-k/dotlocalslashbin/.github/workflows/nox.yaml@a33ce13bfa55aac3dbc6658478e1e91c55003020 # v0.0.18
